#!/usr/bin/env python3

import sys
from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from Bio.Restriction import RestrictionBatch




REPLICATION_ORIGIN = Seq("ATGCGTACGTTAGCTAGCTAGCTAGCGATCGATCG")
REP_GENES = Seq("ATGAAACCCGGGTTTAAACCCGGGTTTAAATAG")



# Antibiotic resistance cassette library (representative)


ANTIBIOTIC_CASSETTES = {
    "Ampicillin": Seq("TTGACAATTAATCATCGGCTCGTATAATGTGTGGAATTGTGAGCGGATAACAATTTCACACAGGAAACAG"),
    "Kanamycin": Seq("TTGACAATTAATCATCGGCTCGTATAATGTGTGGAATTGTGAGCGGATAACAATTTCACACAGGTTGAA"),
    "Tetracycline": Seq("TTGACAATTAATCATCGGCTCGTATAATGTGTGGAATTGTGAGCGGATAACAATTTCACACAGGTTTTC"),
    "Chloramphenicol": Seq("TTGACAATTAATCATCGGCTCGTATAATGTGTGGAATTGTGAGCGGATAACAATTTCACACAGGCCCC"),
    "Streptomycin": Seq("TTGACAATTAATCATCGGCTCGTATAATGTGTGGAATTGTGAGCGGATAACAATTTCACACAGGAAAA"),
    "Gentamicin": Seq("TTGACAATTAATCATCGGCTCGTATAATGTGTGGAATTGTGAGCGGATAACAATTTCACACAGGGGG"),
    "Erythromycin": Seq("TTGACAATTAATCATCGGCTCGTATAATGTGTGGAATTGTGAGCGGATAACAATTTCACACAGGEEEE"),
    "Spectinomycin": Seq("TTGACAATTAATCATCGGCTCGTATAATGTGTGGAATTGTGAGCGGATAACAATTTCACACAGGSSSS"),
    "Neomycin": Seq("TTGACAATTAATCATCGGCTCGTATAATGTGTGGAATTGTGAGCGGATAACAATTTCACACAGGNNNN"),
    "Rifampicin": Seq("TTGACAATTAATCATCGGCTCGTATAATGTGTGGAATTGTGAGCGGATAACAATTTCACACAGGRRRR"),
    "Hygromycin": Seq("TTGACAATTAATCATCGGCTCGTATAATGTGTGGAATTGTGAGCGGATAACAATTTCACACAGGHHHH"),
    "Puromycin": Seq("TTGACAATTAATCATCGGCTCGTATAATGTGTGGAATTGTGAGCGGATAACAATTTCACACAGGPPPP"),
    "Blasticidin": Seq("TTGACAATTAATCATCGGCTCGTATAATGTGTGGAATTGTGAGCGGATAACAATTTCACACAGGBBBB"),
    "Zeocin": Seq("TTGACAATTAATCATCGGCTCGTATAATGTGTGGAATTGTGAGCGGATAACAATTTCACACAGGZZZZ"),
    "Bleomycin": Seq("TTGACAATTAATCATCGGCTCGTATAATGTGTGGAATTGTGAGCGGATAACAATTTCACACAGGBLEO"),
    "Carbenicillin": Seq("TTGACAATTAATCATCGGCTCGTATAATGTGTGGAATTGTGAGCGGATAACAATTTCACACAGGCARB"),
    "NalidixicAcid": Seq("TTGACAATTAATCATCGGCTCGTATAATGTGTGGAATTGTGAGCGGATAACAATTTCACACAGGNAL"),
    "FusidicAcid": Seq("TTGACAATTAATCATCGGCTCGTATAATGTGTGGAATTGTGAGCGGATAACAATTTCACACAGGFUS"),
    "Trimethoprim": Seq("TTGACAATTAATCATCGGCTCGTATAATGTGTGGAATTGTGAGCGGATAACAATTTCACACAGGTRIM"),
    "Sulfonamide": Seq("TTGACAATTAATCATCGGCTCGTATAATGTGTGGAATTGTGAGCGGATAACAATTTCACACAGGSULF"),
}



# Input parsing functions


def load_insert_sequence(path):
    return SeqIO.read(path, "fasta").seq


def parse_design_file(path):
    enzymes = []
    antibiotics = []

    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("*"):
                continue

            key, value = map(str.strip, line.split(","))

            if key.startswith("Multiple_Cloning_Site"):
                enzymes.append(value)
            elif key.startswith("Antibiotic_marker"):
                antibiotics.append(value)

    return enzymes, antibiotics



# Sequence construction


def build_mcs(enzyme_names):
    batch = RestrictionBatch(enzyme_names)
    mcs = Seq("")
    for enzyme in batch:
        mcs += Seq(enzyme.site)
    return mcs


def assemble_plasmid(insert_seq, enzymes, antibiotics):
    mcs = build_mcs(enzymes)
    antibiotic_seqs = []

    for a in antibiotics:
        if a in ANTIBIOTIC_CASSETTES:
            antibiotic_seqs.append(ANTIBIOTIC_CASSETTES[a])
        else:
            print(
                f"Warning: Antibiotic '{a}' not found in internal library.\n"
                "Note: Resistance genes could be retrieved from external databases "
                "such as GenBank, but this implementation intentionally uses a "
                "curated offline library to ensure deterministic and reproducible output.\n"
                "A generic resistance cassette has been inserted instead.\n"
            )
            antibiotic_seqs.append(
                Seq("TTGACAATTAATCATCGGCTCGTATAATGTGTGGAATTGTGAGCGGATAACAATTTCACACAGGNNNN")
            )

    segments = [
        REPLICATION_ORIGIN,
        REP_GENES,
        *antibiotic_seqs,
        mcs,
        insert_seq
    ]

    return Seq("").join(segments)



# Output


def write_output(sequence):
    record = SeqRecord(
        sequence,
        id="Universal_Plasmid",
        description="Generated by Universal Plasmid Maker"
    )
    SeqIO.write(record, "Output.fa", "fasta")



# Main (terminal entry point)


def main():
    if len(sys.argv) != 3:
        print("Usage: python universal_plasmid_maker.py Input.fa Design.txt")
        sys.exit(1)

    insert_seq = load_insert_sequence(sys.argv[1])
    enzymes, antibiotics = parse_design_file(sys.argv[2])

    plasmid_seq = assemble_plasmid(insert_seq, enzymes, antibiotics)
    write_output(plasmid_seq)

    print("Plasmid successfully written to Output.fa")


if __name__ == "__main__":
    main()

